/*
 * Nibble - Concurrent Log-Structured Memory for Many-Core Key-Value Stores
 *
 * (c) 2017 Hewlett Packard Enterprise Development LP.
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version. This program is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>. As an exception, the copyright holders of this Library
 * grant you permission to (i) compile an Application with the Library, and (ii) distribute the Application
 * containing code generated by the Library and added to the Application during this compilation process
 * under terms of your choice, provided you also meet the terms and conditions of the Application license.
 */


#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(dead_code)]
#![feature(const_fn)]

extern crate kvs;

// use kvs::clock;
use kvs::common::{Pointer,ErrorCode,rdrand,rdrandq};
// use kvs::epoch;
use kvs::logger;
// use kvs::memory;
use kvs::lsm::{self,LSM};
use kvs::numa::{self,NodeId};
// use kvs::sched::*;
// use kvs::segment::{ObjDesc,SEGMENT_SIZE};
// use rand::Rng;
// use std::collections::VecDeque;
// use std::mem;
// use std::sync::Arc;
// use std::sync::atomic::*;
use std::thread::{self,JoinHandle};
use std::time::{Instant,Duration};
use std::ptr::null;

static mut KVS: Pointer<LSM> = Pointer(null::<LSM>());

#[no_mangle] pub extern
fn kvs_init(cap: usize, nitems: usize) {
	logger::enable();
	println!("# LSM allocating...");
	//let kvs: Box<LSM> = Box::new(LSM::default());
	let kvs: Box<LSM> = Box::new(LSM::new2(cap,nitems));
	println!("# LSM enabling compaction");
	for sock in 0..numa::NODE_MAP.sockets() {
		kvs.enable_compaction(NodeId(sock));
	}
	let p = Box::into_raw(kvs);
	println!("# LSM @ {:?}", p);
	unsafe {
		KVS.0 = p;
	}
}

#[no_mangle] pub extern
fn kvs_alloc(key: u64, len: u64, sock: u32) -> *const u8 {
	let kvs: &LSM = unsafe { &*KVS.0 };
	// println!("alloc {:x}", key);
	kvs.alloc(key, len, sock).0
}

#[no_mangle] pub extern
fn kvs_free(key: u64, fail: i32) {
	let kvs: &LSM = unsafe { &*KVS.0 };
	// println!("free {:x}", key);
	let ret = kvs.free(key);
    assert!((1 == fail) && ret,
        "key {} not found upon deletion", key);
}
