#! /usr/bin/env bash
set -e
set -u


export NIBDEBUG=3
export RAMCLOUD_ARGV="-t 16384 -h 10%"
# number of args + 1 (like 'int argc' in C main)
export RAMCLOUD_NARG=5

FEATURES="extern_ycsb rc"

nthreads=8
size=100
readpct=95
nkeys=$((10**6))
# in MiB
capacity=$((2**10))
# zipfian or uniform
dist="uniform"

cargo run --features "$FEATURES" --release --bin ycsb -- \
    --dist $dist \
    --readpct $readpct \
    --records $nkeys \
    --capacity $capacity \
    --ops 0 \
    --threads $nthreads \
    --time 20 \
    --cpu rr \
    --put local \
    --size $size

