#! /usr/bin/env bash
set -e
set -u

export NIBDEBUG=3

(
    scripts/sysinfo
    echo '';echo ''
    cargo run --bin pipeline_scale --release -- \
        --min 9 \
        --max 144 \
        --incr 9 \
        --size 1000 \
        --cap 500
) 2>&1 | tee pipeline.log

