#! /usr/bin/env bash
set -e
set -u

echo 0 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
echo 0 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

echo '[Huge Pages]:'
echo -n '2MB huge pages: '
cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
echo -n '1GB huge pages: '
cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
