/*
 * Nibble - Concurrent Log-Structured Memory for Many-Core Key-Value Stores
 *
 * (c) 2017 Hewlett Packard Enterprise Development LP.
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version. This program is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>. As an exception, the copyright holders of this Library
 * grant you permission to (i) compile an Application with the Library, and (ii) distribute the Application
 * containing code generated by the Library and added to the Application during this compilation process
 * under terms of your choice, provided you also meet the terms and conditions of the Application license.
 */


#![feature(test)]
#![feature(const_fn)]
#![feature(asm)]
#![feature(repr_simd)]
#![feature(integer_atomics)]

// used for kvs/tlock.rs
#![feature(core_intrinsics)]

// Clippy tool
//#![feature(plugin)]
//#![plugin(clippy)]

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

// Used for likely/unlikely
#![feature(core_intrinsics)]

// Remove these XXX
#![allow(dead_code)]
#![allow(unreachable_code)]

#![forbid(const_err)]

#[macro_use]
extern crate log;

#[macro_use]
extern crate lazy_static;

extern crate libc;
extern crate rand;
extern crate test;
extern crate time;
extern crate crossbeam;
extern crate itertools;
extern crate quicksort;
extern crate syscall;
extern crate parking_lot;
extern crate num;

pub mod kvs;
pub use kvs::*;
